# This is an example .github/workflows/deploy-functions.yml file.

name: Deploy Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "$GHUB_PAT"